package be.hasan.libraSphere.books;
public enum Genre {
    ADVENTURE, BIOGRAPHY, CLASSICS, COMIC_GRAPHIC_NOVEL, CRIME_DETECTIVE,
    DRAMA, FANTASY, HISTORICAL_FICTION, HORROR, LITERARY_FICTION, MYSTERY,
    NON_FICTION, POETRY, ROMANCE, SCIENCE_FICTION, SHORT_STORY, SUSPENSE_THRILLER,
    YOUNG_ADULT, CHILDREN, SELF_HELP, TRAVEL, COOKBOOKS, MEMOIR, RELIGION_SPIRITUALITY,
    SCIENCE, HISTORY, PHILOSOPHY, ART, MUSIC, REFERENCE, TRUE_CRIME, EDUCATION, HEALTH,
    SPORTS, ANTHOLOGY, ESSAYS, FAIRY_TALES, SATIRE, TECHNOLOGY
}
